/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    staff: Staff;
    reviews: Review;
    customers: Customer;
    appointments: Appointment;
    pages: Page;
    gallery: Gallery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    navbar: Navbar;
    footer: Footer;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title?: string | null;
  description?: string | null;
  price?: number | null;
  duration?: number | null;
  image?: (string | null) | Media;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: string;
  name?: string | null;
  bio?: string | null;
  speciality?: string | null;
  photo?: (string | null) | Media;
  services?: (string | null) | Service;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok' | 'pinterest';
        url: string;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  customer?: (string | null) | Customer;
  appointment?: (string | null) | Appointment;
  service?: (string | null) | Service;
  staff?: (string | null) | Staff;
  visitType?: ('appointment' | 'walk-in') | null;
  rating?: number | null;
  experience?: ('excellent' | 'good' | 'regular' | 'bad') | null;
  comments?: string | null;
  isAnonymous?: boolean | null;
  submittedForm?: ('reception' | 'web' | 'qr') | null;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  email?: string | null;
  preferredContactMethod?: ('whatsapp' | 'email' | 'phone') | null;
  allowNotifications?: boolean | null;
  status?: ('active' | 'inactive' | 'blocked') | null;
  lastVisit?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  customer?: (string | null) | Customer;
  service?: (string | null) | Service;
  staff?: (string | null) | Staff;
  date?: string | null;
  time?: string | null;
  status?: ('pending' | 'confirmed' | 'completed' | 'cancelled' | 'no-show') | null;
  source?: ('web' | 'reception' | 'whatsapp' | 'phone') | null;
  customerNotes?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL-friendly identifier for the page
   */
  slug: string;
  /**
   * Add and arrange blocks to build your page layout
   */
  layout: (
    | {
        /**
         * Small text label above the title
         */
        badge: string;
        /**
         * Main hero title (supports line breaks)
         */
        title: string;
        /**
         * The text that will be colored in red
         */
        highlightedText: string;
        /**
         * Main description text
         */
        description: string;
        /**
         * The background image for the hero section
         */
        backgroundImage: string | Media;
        buttons?: {
          /**
           * Primary CTA button text
           */
          primaryButtonText?: string | null;
          /**
           * Primary CTA button text for mobile
           */
          primaryButtonShortText?: string | null;
          /**
           * Secondary button text
           */
          secondaryButtonText?: string | null;
          /**
           * Secondary button text for mobile
           */
          secondaryButtonShortText?: string | null;
        };
        /**
         * Select services to display in the hero section (optional)
         */
        services?: (string | Service)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero-block';
      }
    | {
        title: string;
        subtitle: string;
        /**
         * Seleccione los servicios que apareceran en la sección
         */
        services: (string | Service)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'service-block';
      }
    | {
        title: string;
        subtitle: string;
        /**
         * Personal del negocio
         */
        staff: (string | Staff)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'staff-block';
      }
    | {
        title: string;
        subtitle: string;
        /**
         * Imagenes de galeria
         */
        gallery: (string | Gallery)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery-block';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  title: string;
  image: string | Media;
  tags?: ('cortes' | 'barberia' | 'estilo' | 'clientes' | 'antes-despues')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'staff';
        value: string | Staff;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  price?: T;
  duration?: T;
  image?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  speciality?: T;
  photo?: T;
  services?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  customer?: T;
  appointment?: T;
  service?: T;
  staff?: T;
  visitType?: T;
  rating?: T;
  experience?: T;
  comments?: T;
  isAnonymous?: T;
  submittedForm?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  email?: T;
  preferredContactMethod?: T;
  allowNotifications?: T;
  status?: T;
  lastVisit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  customer?: T;
  service?: T;
  staff?: T;
  date?: T;
  time?: T;
  status?: T;
  source?: T;
  customerNotes?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        'hero-block'?:
          | T
          | {
              badge?: T;
              title?: T;
              highlightedText?: T;
              description?: T;
              backgroundImage?: T;
              buttons?:
                | T
                | {
                    primaryButtonText?: T;
                    primaryButtonShortText?: T;
                    secondaryButtonText?: T;
                    secondaryButtonShortText?: T;
                  };
              services?: T;
              id?: T;
              blockName?: T;
            };
        'service-block'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        'staff-block'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              staff?: T;
              id?: T;
              blockName?: T;
            };
        'gallery-block'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              gallery?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: string;
  /**
   * Gestion de los links de navegación
   */
  navigationLinks?:
    | {
        label: string;
        link: string;
        isSection: boolean;
        isModal: boolean;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  description: string;
  /**
   * Add social media links
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: string;
  /**
   * The name of your website
   */
  siteName: string;
  /**
   * A short tagline or motto for your business
   */
  tagline?: string | null;
  /**
   * Main logo used across the site
   */
  logo: string | Media;
  /**
   * Browser tab icon (preferably 32x32px)
   */
  favicon?: (string | null) | Media;
  theme?: {
    /**
     * Primary brand color (hex format)
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color (hex format)
     */
    secondaryColor?: string | null;
    /**
     * Default background color
     */
    background?: string | null;
    /**
     * Default text color
     */
    textColor?: string | null;
  };
  seo?: {
    /**
     * Used as the default title tag on pages without a specific title
     */
    defaultTitle?: string | null;
    /**
     * Default Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
    /**
     * Allow search engines to index your website
     */
    indexingEnabled?: boolean | null;
  };
  contact: {
    /**
     * Primary phone number for customer inquiries
     */
    phone: string;
    /**
     * Primary contact email
     */
    email: string;
    /**
     * Your physical business location
     */
    address: string;
    /**
     * WhatsApp number for customer contact
     */
    whatsapp?: string | null;
  };
  /**
   * Add social media profiles linked from your site
   */
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok' | 'pinterest';
        url: string;
        id?: string | null;
      }[]
    | null;
  booking?: {
    /**
     * Enable or disable the booking system
     */
    enabled?: boolean | null;
    /**
     * Duration of each booking slot in minutes
     */
    slotDuration?: number | null;
    /**
     * Display your business hours
     */
    openHours?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  navigationLinks?:
    | T
    | {
        label?: T;
        link?: T;
        isSection?: T;
        isModal?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  theme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        background?: T;
        textColor?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        ogImage?: T;
        indexingEnabled?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        whatsapp?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  booking?:
    | T
    | {
        enabled?: T;
        slotDuration?: T;
        openHours?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}